name: GitHub CI

on: [pull_request, push]

# for some reason, this does not work:
# variables:
#   BUILDOPTS: "-j4"
#   HARNESS_JOBS: "${HARNESS_JOBS:-4}"

# for some reason, this does not work:
# before_script:
#     - make="make -s"

jobs:
  basic_gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: ./config --strict-warnings && perl configdata.pm --dump
    - name: make
      run: |
        gcc -v
        cat cpp.add >>Makefile
        make build_generated
        make crypto/asn1/a_mbstr.i
        grep -n -B5 UNICODE_ crypto/asn1/a_mbstr.i
        make crypto/asn1/libcrypto-shlib-a_mbstr.o
        make crypto/asn1/libcrypto-shlib-a_utf8.o
